django_start/urls.py
from django.contrib import admin
from django.urls import include, path

from basic import views
from basic import views_login
from basic.views_fehler import error_500, error_404

from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('', views.start, name='start'),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('login/', views_login.basic_login, name='mysite_basic_login'),
    path('logout/', views_login.basic_logout, name='mysite_basic_logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(template_name='basic/password_change_form.html'),
         name='mysite_basic_change'),
    path('accounts/password_change_done/',
         PasswordChangeDoneView.as_view(template_name='basic/password_change_done.html'), name='password_change_done'),
    path('start/', views.startpage, name='mysite_startpage'),
    path('end/', views.logoutpage, name='mysite_logoutpage'),
    path('error/', views.errorpage, name='mysite_errorpage'),
    path('edms/', include('dmsapp.urls', namespace='dms')),
    path('webdms/', include('webdms.urls', namespace='web_scribble_notes')),
]

handler404 = error_404
handler500 = error_500

dmsapp/urls.py
from django.urls import path
from .views import file_import, datei_download

app_name = 'dms'

# dms
urlpatterns = [
    path('datei/<str:pathslug>/<str:dateislug>', datei_download, name='dateidownload'),
    path('fileimport/<slug:treeslug>', file_import, name='fileimport'),
]

webdms/urls.py
from django.urls import path, include
# from django.contrib import admin
from .view_book import change_book, book_view, book_add, book_edit, book_backup, book_restore, \
    book_viewtemp, book_media
from .view_keywords import schluessel_add, schluessel_edit, schluessel_find, schluessel_view, schluessel_view_notes
from .view_note import datei_view, datei_add, datei_change, note_delete, datei_fehler, datei_view_book
from .view_url import tree_error, url_change, url_add, menu_add
from .views import index_view, tree_empty, menu_view
from .view_search import search_view
app_name = 'webdms'


# webdms:
urlpatterns = [
    # 'webdms/'
    path('', index_view, name='index'),
    path('menu/', menu_view, name='menu'),
    # path('menu/<str:pathslug>/', menu_add, name='menu_add'),
    path('book/', book_view, name='bookview'),
    path('bookadd/', book_add, name='bookadd'),
    path('bookedit/<slug:bookslug>/', book_edit, name='bookedit'),
    # path('bookdelete/<slug:bookslug>/', book_delete, name='bookdelete'),
    path('bookbackup/', book_backup, name='bookbackup'),
    path('bookrestore/', book_restore, name='bookrestore'),
    path('bookmedia/<str:todo>/<str:dateiname>/', book_media, name='bookmedia'),
    path('booktemp/', book_viewtemp, name='bookviewtemp'),
    path('bookchange/<slug:bookslug>/', change_book, name='changebook'),
    path('path/', include('webdms.wspath.urls', namespace='path')),
    path('tree/<str:pfadslug>/fehlernote/<int:fehlerid>/', datei_fehler, name='notefehler'),
    path('treeadd/', url_add, name='treeadd'),
    path('treeadd/<str:pathslug>/', menu_add, name='menu_add'),
    path('treechange/', url_change, name='treechange'),  # hier wird URL gefüllt
    path('treeempty/', tree_empty, name='treeempty'),
    path('treerror/<int:error>/', tree_error, name='treeerror'),
    path('note/<slug:treeslug>/<slug:noteslug>', datei_view, name='noteview'),
    path('notebook/<slug:bookslug>/<slug:treeslug>/<slug:noteslug>', datei_view_book, name='notesviewbook'),
    path('noteadd/<slug:treeslug>', datei_add, name='noteadd'),
    path('notechange/<slug:noteslug>', datei_change, name='notechange'),
    path('notedelete/<slug:noteslug>', note_delete, name='notedelete'),
    # path('noteimport/<slug:treeslug>', note_import, name='noteimport'),
    # noch nicht fertig
    path('keywords', schluessel_view, name='keywords_view'),
    path('keywordadd', schluessel_add, name='keywordadd'),
    path('keyword/<slug:keyslug>/', schluessel_edit, name='keywordsedit'),
    path('keywordfind/<slug:keyslug>/', schluessel_find, name='schluesselfind'),
    path('keywordview/<slug:bookslug>/<slug:keyslug>/<slug:dateislug>', schluessel_view_notes, name='keywordsviewnotes'),
    path('suchen/', search_view, name='search'),
]

basic/models.py
from django.db import models
from django.contrib.auth.models import User, Group


class Gruppe(models.Model):
    """
      zum festlegen, was die Hauptgruppe (zur Zeit ist)
      wenn Hauptuser, Admins mitglied mehrerer Gruppen sind und innerhalb einer Gruppe arbeiten sollen
    """
    user = models.OneToOneField(User, on_delete=models.CASCADE, )
    group = models.ForeignKey(Group, on_delete=models.CASCADE, )

    def __str__(self):
        return str(self.user)

    class Meta:
        unique_together = ('user', 'group')

basic/forms.py
from .models import User

# from django import forms
from django.forms import ModelForm


# nur für Lokale User in SSO auskommentieren
class UserForm(ModelForm):
    class Meta:
        model = User
        exclude = ('last_login', 'date_joined')

basic/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse


def startpage(request):
    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse('web_scribble_notes:index', args=[]))
    else:
        return HttpResponseRedirect(reverse('mysite_basic_login', args=[]))


def start(request):
    angemeldet = request.user.is_authenticated
    if angemeldet:
        return HttpResponseRedirect(reverse('web_scribble_notes:index', args=[]))
    dictionary = {
        'angemeldet': angemeldet,
        'error': False,
        'titel': 'Start',
    }
    return render(request, 'basic/start.html', dictionary)


def logoutpage(request):
    return render(request, 'basic/start.html', {'angemeldet': False, 'titel': 'abgemeldet', 'error': False})


def errorpage(request):
    if request.user.is_authenticated:
        return render(request, 'basic/keine-gruppe.html', {'angemeldet': False, 'error': False})
    else:
        return render(request, 'basic/start.html', {'angemeldet': False, 'titel': 'Fehler', 'error': True})

basic/templates/__error-anmeldung.html
<div class="container-fluid">

  <!-- Page Heading -->
  <div class="d-sm-flex align-items-center justify-content-between mb-4">
  </div>

  <!-- Content Row -->
  <div class="row">

    <div class="col-lg-10 mb-4">

      <!-- Approach -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'mysite_basic_login' %}">Fehler bei der Anmeldung</a></h6>
        </div>
        <div class="card-body">
                <p>Benutzername / Passwort stimmen nicht oder sind nicht vorhanden</p>
        </div>
      </div>
    </div>

    <!-- Content Column -->
    <div class="col-lg-6 mb-4"></div>

  </div>

</div>

basic/templates/__error-gruppe.html
<div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">

          </div>

          <!-- Content Row -->
          <div class="row">

            <div class="col-lg-10 mb-4">

              <!-- Approach -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                  <h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'mysite_basic_login' %}">System ohne Gruppe</a></h6>
                </div>
                <div class="card-body">
                        <p>Dem Benutzer ist noch keine Gruppe zugeordnet.</p>
                </div>
              </div>

            </div>

            <!-- Content Column -->
            <div class="col-lg-6 mb-4">


            </div>

          </div>

        </div>

basic/templates/__footer.html
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
{#            <span>Copyright &copy; Your Website 2019</span>#}
            <span>Copyright &copy; {% include "_project.html" %} 2019</span>
          </div>
        </div>
      </footer>

basic/templates/__page-content.html
<div class="container-fluid">
          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
{#            <h1 class="h3 mb-0 text-gray-800">Dashboard</h1>#}
{#            <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm"><i class="fas fa-download fa-sm text-white-50"></i> Generate Report</a>#}
          </div>

          <!-- Content Row -->
          <div class="row">

{#            <div class="col-lg-6 mb-4">#}
            <div class="col-lg-10 mb-4">

              <!-- Approach -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                    {% if angemeldet %}
                        <h6 class="m-0 font-weight-bold text-primary">Erfolgreich angemeldet</h6>
                    {% else %}
                  <h6 class="m-0 font-weight-bold text-primary"><a href="{% url 'mysite_basic_login' %}">Startseite</a></h6>
                    {% endif %}
                </div>
                <div class="card-body">
                    <p>Basisinformationen hier anzeigen und Links zu Daten die gegebenenfalls auf ein Login umgelenkt werden</p>
                    <p>Auch ein nettes Hintergrundbild macht Sinn, da die Menüs ausgeblendet sind, bis der Login erfolgt ist.</p>
{#                  <p>SB Admin 2 makes extensive use of Bootstrap 4 utility classes in order to reduce CSS bloat and poor page performance. Custom CSS classes are used to create custom components and custom utility classes.</p>#}
{#                  <p class="mb-0">Before working with this theme, you should become familiar with the Bootstrap framework, especially the utility classes.</p>#}
                    {% if request.user.is_active %}
                        <div class="row">
                            <div class="col-lg-5"><p><a href="{% url 'web_scribble_notes:treeadd' %}">Tree anlegen (Menü auf Linker Seite)</a></p></div>
                            <div class="col-lg-5"><p><a href="{% url 'web_scribble_notes:treechange' %}">Tree ändern (Menü auf Linker Seite)</a></p></div>
                        </div>
                    {% endif %}
                </div>
              </div>

            </div>

            <!-- Content Column -->
            <div class="col-lg-6 mb-4">

              <!-- Project Card Example -->

              <!-- Color System -->
{% comment %}
              <div class="row">
                <div class="col-lg-6 mb-4">
                  <div class="card bg-primary text-white shadow">
                    <div class="card-body">
                      Primary
                      <div class="text-white-50 small">#4e73df</div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 mb-4">
                  <div class="card bg-success text-white shadow">
                    <div class="card-body">
                      Success
                      <div class="text-white-50 small">#1cc88a</div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 mb-4">
                  <div class="card bg-info text-white shadow">
                    <div class="card-body">
                      Info
                      <div class="text-white-50 small">#36b9cc</div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 mb-4">
                  <div class="card bg-warning text-white shadow">
                    <div class="card-body">
                      Warning
                      <div class="text-white-50 small">#f6c23e</div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 mb-4">
                  <div class="card bg-danger text-white shadow">
                    <div class="card-body">
                      Danger
                      <div class="text-white-50 small">#e74a3b</div>
                    </div>
                  </div>
                </div>
                <div class="col-lg-6 mb-4">
                  <div class="card bg-secondary text-white shadow">
                    <div class="card-body">
                      Secondary
                      <div class="text-white-50 small">#858796</div>
                    </div>
                  </div>
                </div>
              </div>
{% endcomment %}

            </div>

          </div>

        </div>

basic/templates/__sidebar.html
{#<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">#}
<ul class="navbar-nav bg-primary sidebar sidebar-dark accordion" id="accordionSidebar">

      <!-- Sidebar - Brand -->
{% comment %}      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% static 'index.html' %}">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
      </a>{% endcomment %}
{% comment %}      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'web_scribble_notes:index' %}">
          <div class="sidebar-brand-text mx-3">Start</div>
      </a>{% endcomment %}

      <!-- Divider -->
      <hr class="sidebar-divider my-0">

      <!-- Nav Item - Dashboard -->
{#        {% include "web_scribble_notes/toggle_tree.html" %}#}
{#        {% include "web_scribble_notes/toggle_path.html" %}#}
{#        {% include "web_scribble_notes/toggle_path_jstree.html" %}#}
        {% include "webdms/toggle_path_static.html" %}
{#      <li class="nav-item active">#}
{#        <a class="nav-link" href="{% static 'index.html' %}">#}
{#          <i class="fas fa-fw fa-tachometer-alt"></i>#}
{#          <span>Dashboard</span></a>#}
{#      </li>#}

      <!-- Divider -->
{#      <hr class="sidebar-divider">#}

      <!-- Heading -->
{#      <div class="sidebar-heading">#}
{#        Tags#}
{#      </div>#}

      <!-- Nav Item - Pages Collapse Menu -->
{#      <li class="nav-item">#}
{#        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">#}
{#          <i class="fas fa-fw fa-cog"></i>#}
{#          <span>Components</span>#}
{#        </a>#}
{#        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">#}
{#          <div class="bg-white py-2 collapse-inner rounded">#}
{#            <h6 class="collapse-header">Custom Components:</h6>#}
{#            <a class="collapse-item" href="{% static 'buttons.html' %}">Buttons</a>#}
{#            <a class="collapse-item" href="{% static 'cards.html' %}">Cards</a>#}
{#          </div>#}
{#        </div>#}
{#      </li>#}

      <!-- Nav Item - Utilities Collapse Menu -->
{#      <li class="nav-item">#}
{#        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">#}
{#          <i class="fas fa-fw fa-wrench"></i>#}
{#          <span>Utilities</span>#}
{#        </a>#}
{#        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">#}
{#          <div class="bg-white py-2 collapse-inner rounded">#}
{#            <h6 class="collapse-header">Custom Utilities:</h6>#}
{#            <a class="collapse-item" href="{% static 'utilities-color.html' %}">Colors</a>#}
{#            <a class="collapse-item" href="{% static 'utilities-border.html' %}">Borders</a>#}
{#            <a class="collapse-item" href="{% static 'utilities-animation.html' %}">Animations</a>#}
{#            <a class="collapse-item" href="{% static 'utilities-other.html' %}">Other</a>#}
{#          </div>#}
{#        </div>#}
{#      </li>#}
{##}
{#      <!-- Divider -->#}
{#      <hr class="sidebar-divider">#}
{##}
{#      <!-- Heading -->#}
{#      <div class="sidebar-heading">#}
{#        Addons#}
{#      </div>#}

      <!-- Nav Item - Pages Collapse Menu -->
{#      <li class="nav-item">#}
{#        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">#}
{#          <i class="fas fa-fw fa-folder"></i>#}
{#          <span>Pages</span>#}
{#        </a>#}
{#        <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">#}
{#          <div class="bg-white py-2 collapse-inner rounded">#}
{#            <h6 class="collapse-header">Login Screens:</h6>#}
{#            <a class="collapse-item" href="{% static 'login.html' %}">Login</a>#}
{#            <a class="collapse-item" href="{% static 'register.html' %}">Register</a>#}
{#            <a class="collapse-item" href="{% static 'forgot-password.html' %}">Forgot Password</a>#}
{#            <div class="collapse-divider"></div>#}
{#            <h6 class="collapse-header">Other Pages:</h6>#}
{#            <a class="collapse-item" href="{% static '404.html' %}">404 Page</a>#}
{#            <a class="collapse-item" href="{% static 'blank.html' %}">Blank Page</a>#}
{#          </div>#}
{#        </div>#}
{#      </li>#}

      <!-- Nav Item - Charts -->
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="{% static 'charts.html' %}">#}
{#          <i class="fas fa-fw fa-chart-area"></i>#}
{#          <span>Charts</span></a>#}
{#      </li>#}

      <!-- Nav Item - Tables -->
{#      <li class="nav-item">#}
{#        <a class="nav-link" href="{% static 'tables.html' %}">#}
{#          <i class="fas fa-fw fa-table"></i>#}
{#          <span>Tables</span></a>#}
{#      </li>#}

      <!-- Divider -->
{#      <hr class="sidebar-divider d-none d-md-block">#}

      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>

    </ul>

basic/templates/__topbar.html
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>

          <!-- Topbar Search -->
          {% include "_toolbar_search.html" %}

          <div class="d-sm-flex align-items-center justify-content-between">
              {% include "webdms/toggle_new-delete_button.html" %}
          </div>

          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">

            <!-- Nav Item - Search Dropdown (Visible Only XS) -->

{#            <button type="button" class="btn btn-primary btn-sm">Seite anlegen</button>#}

            <!-- Nav Item - Alerts -->
{#            {% include "_nav-item-alerts.html" %}#}
            {% include "webdms/_nav-item-schluessel.html" %}
            <!-- Nav Item - Messages -->

            {% include "webdms/toggle_books.html" %}

            <!-- Nav Item - User Information -->
            {% include "_nav-item-userinformation.html" %}

          </ul>

        </nav>

basic/templates/_nav-item-alerts.html
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-primary">
                      <i class="fas fa-file-alt text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 12, 2019</div>
                    <span class="font-weight-bold">A new monthly report is ready to download!</span>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-success">
                      <i class="fas fa-donate text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 7, 2019</div>
                    $290.29 has been deposited into your account!
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="mr-3">
                    <div class="icon-circle bg-warning">
                      <i class="fas fa-exclamation-triangle text-white"></i>
                    </div>
                  </div>
                  <div>
                    <div class="small text-gray-500">December 2, 2019</div>
                    Spending Alert: We've noticed unusually high spending for your account.
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
              </div>
            </li>

basic/templates/_nav-item-messages.html
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                  Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div class="font-weight-bold">
                    <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
                    <div class="small text-gray-500">Emily Fowler · 58m</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
                    <div class="status-indicator"></div>
                  </div>
                  <div>
                    <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
                    <div class="small text-gray-500">Jae Chun · 1d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
                    <div class="status-indicator bg-warning"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
                    <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                  </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                  <div class="dropdown-list-image mr-3">
                    <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
                    <div class="status-indicator bg-success"></div>
                  </div>
                  <div>
                    <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
                    <div class="small text-gray-500">Chicken the Dog · 2w</div>
                  </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
              </div>
            </li>

basic/templates/_nav-item-search.html
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages -->
              <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                  <div class="input-group">
                    <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
                    <div class="input-group-append">
                      <button class="btn btn-primary" type="button">
                        <i class="fas fa-search fa-sm"></i>
                      </button>
                    </div>
                  </div>
                </form>
              </div>
            </li>

basic/templates/_nav-item-userinformation.html
{% load static %}
{% load rechte_helper %}
<div class="topbar-divider d-none d-sm-block"></div>

<li class="nav-item dropdown no-arrow">
  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
    <img class="img-profile rounded-circle" src="{% static 'img/149452.svg' %}" title="{{ user.first_name }} {{ user.last_name }}">
  </a>
  <!-- Dropdown - User Information -->
  <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
    <a class="dropdown-item" href="{% url 'mysite_basic_change' %}">
      <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
      Profile
    </a>
    <a class="dropdown-item" href="{% if book %}{% url 'web_scribble_notes:bookbackup' %}{% else %}#{% endif %}">
      <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
      Backup
    </a>
    <a class="dropdown-item" href="{% url 'web_scribble_notes:bookrestore' %}">
      <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
      Restore
    </a>
{% comment %}    <a class="dropdown-item" href="{% if pathslug %}{% url 'web_scribble_notes:path:noteimport' pathslug %}{% else %}{% url 'web_scribble_notes:path:noteimport' None %}{% endif %}" title="TXT-HTML-Dateien">
      <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
      Import
    </a>{% endcomment %}
    <a class="dropdown-item" href="{% url 'web_scribble_notes:menu' %}">
      <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
      Menü
    </a>
    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
      <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
      Abmelden
    </a>
  </div>
</li>

basic/templates/_project.html
Web-DMS

basic/templates/_toolbar_search.html
{% comment %}<form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
        <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search"
               aria-describedby="basic-addon2">
        <div class="input-group-append">
            <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
            </button>
        </div>
    </div>
</form>{% endcomment %}
<div class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100"></div>

basic/templates/tree_error__content.html
<div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4"></div>

          <!-- Content Row -->
          <div class="row">

            <div class="col-lg-10 mb-4">

              <!-- Approach -->
              <div class="card shadow mb-4">
                <div class="card-header py-3">
                        <h6 class="m-0 font-weight-bold text-primary">{{ cardheader }}</h6>
                </div>
                <div class="card-body">
                    {% if request.user.is_active %}
                        <div class="row">
                            <div class="col-lg-5">{{ msg }}</div>
                        </div>
                        {% if errshowmenu %}
                            <br />
                            <div class="row">
                                <div class="col-lg-5"><a href="{% url 'webdms:menu' %}">Menü bearbeiten</a> </div>
                            </div>
                        {% endif %}
                    {% endif %}
                </div>
              </div>

            </div>

            <!-- Content Column -->
            <div class="col-lg-6 mb-4"><!-- Project Card Example --></div>

          </div>

        </div>