django_start/urls.py
from django.contrib import admin
from django.urls import include, path

from basic import views
from basic import views_login
from basic.views_fehler import error_500, error_404

from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('', views.start, name='start'),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('login/', views_login.basic_login, name='mysite_basic_login'),
    path('logout/', views_login.basic_logout, name='mysite_basic_logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(template_name='basic/password_change_form.html'),
         name='mysite_basic_change'),
    path('accounts/password_change_done/',
         PasswordChangeDoneView.as_view(template_name='basic/password_change_done.html'), name='password_change_done'),
    path('start/', views.startpage, name='mysite_startpage'),
    path('end/', views.logoutpage, name='mysite_logoutpage'),
    path('error/', views.errorpage, name='mysite_errorpage'),
    path('edms/', include('dmsapp.urls', namespace='dms')),
    path('webdms/', include('webdms.urls', namespace='web_scribble_notes')),
]

handler404 = error_404
handler500 = error_500

dmsapp/urls.py
from django.urls import path
from .views import file_import, datei_download

app_name = 'dms'

# dms
urlpatterns = [
    path('datei/<str:pathslug>/<str:dateislug>', datei_download, name='dateidownload'),
    path('fileimport/<slug:treeslug>', file_import, name='fileimport'),
]

webdms/urls.py
from django.urls import path, include
# from django.contrib import admin
from .view_book import change_book, book_view, book_add, book_edit, book_backup, book_restore, \
    book_viewtemp, book_media
from .view_keywords import schluessel_add, schluessel_edit, schluessel_find, schluessel_view, schluessel_view_notes
from .view_note import datei_view, datei_add, datei_change, note_delete, datei_fehler, datei_view_book
from .view_url import tree_error, url_change, url_add, menu_add
from .views import index_view, tree_empty, menu_view
from .view_search import search_view
app_name = 'webdms'


# webdms:
urlpatterns = [
    # 'webdms/'
    path('', index_view, name='index'),
    path('menu/', menu_view, name='menu'),
    # path('menu/<str:pathslug>/', menu_add, name='menu_add'),
    path('book/', book_view, name='bookview'),
    path('bookadd/', book_add, name='bookadd'),
    path('bookedit/<slug:bookslug>/', book_edit, name='bookedit'),
    # path('bookdelete/<slug:bookslug>/', book_delete, name='bookdelete'),
    path('bookbackup/', book_backup, name='bookbackup'),
    path('bookrestore/', book_restore, name='bookrestore'),
    path('bookmedia/<str:todo>/<str:dateiname>/', book_media, name='bookmedia'),
    path('booktemp/', book_viewtemp, name='bookviewtemp'),
    path('bookchange/<slug:bookslug>/', change_book, name='changebook'),
    path('path/', include('webdms.wspath.urls', namespace='path')),
    path('tree/<str:pfadslug>/fehlernote/<int:fehlerid>/', datei_fehler, name='notefehler'),
    path('treeadd/', url_add, name='treeadd'),
    path('treeadd/<str:pathslug>/', menu_add, name='menu_add'),
    path('treechange/', url_change, name='treechange'),  # hier wird URL gefüllt
    path('treeempty/', tree_empty, name='treeempty'),
    path('treerror/<int:error>/', tree_error, name='treeerror'),
    path('note/<slug:treeslug>/<slug:noteslug>', datei_view, name='noteview'),
    path('notebook/<slug:bookslug>/<slug:treeslug>/<slug:noteslug>', datei_view_book, name='notesviewbook'),
    path('noteadd/<slug:treeslug>', datei_add, name='noteadd'),
    path('notechange/<slug:noteslug>', datei_change, name='notechange'),
    path('notedelete/<slug:noteslug>', note_delete, name='notedelete'),
    # path('noteimport/<slug:treeslug>', note_import, name='noteimport'),
    # noch nicht fertig
    path('keywords', schluessel_view, name='keywords_view'),
    path('keywordadd', schluessel_add, name='keywordadd'),
    path('keyword/<slug:keyslug>/', schluessel_edit, name='keywordsedit'),
    path('keywordfind/<slug:keyslug>/', schluessel_find, name='schluesselfind'),
    path('keywordview/<slug:bookslug>/<slug:keyslug>/<slug:dateislug>', schluessel_view_notes, name='keywordsviewnotes'),
    path('suchen/', search_view, name='search'),
]

webdms/wspath/urls.py
from django.urls import path
from .path import path_view, path_datei, path_dateichange, datei_add, path_empty, path_dateiempty, \
    path_delete, path_alle, path_tree, searchsl_view
app_name = 'notes_path'


# webdms:path:datei
urlpatterns = [
    # 'webdms/path/' ...
    path('add/<str:pathslug>/', datei_add, name='add'),
    path('alle/', path_alle, name='alle'),
    path('empty/', path_empty, name='empty'),
    path('datei/<str:pathslug>/<slug:dateislug>/', path_datei, name='datei'),
    path('view/<str:pathslug>/', path_view, name='view'),
    path('change/<slug:dateislug>/', path_dateichange, name='notechange'),
    path('delete/<slug:dateislug>/', path_delete, name='delete'),
    path('dateiempty/<slug:dateislug>/', path_dateiempty, name='dateiempty'),
    path('suchen/<str:pathslug>/', searchsl_view, name='searchsl'),
    path('tree/<str:pathslug>/', path_tree, name='treechange'),
]

webdms/models.py
from django.db import models
from django.contrib.auth.models import Group
# from django.contrib.auth.models import User, Permission  # für Lokale Userverwaltung
from django.utils.text import slugify
# from django.conf import settings
# from tinymce.models import HTMLField
from uuid import uuid4
import itertools


class Books(models.Model):
    """Book where the Files (Dateien) are in"""
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    book = models.CharField(max_length=32, db_index=True)
    slug = models.SlugField(max_length=36, null=True, blank=True)
    gruppe = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, db_index=True)
    is_active = models.BooleanField(default=False)
    bookroot = models.CharField(max_length=256, default='', blank=True)
    directory = models.CharField(max_length=126, default='', blank=True)
    datum_created = models.DateTimeField(auto_now_add=True, editable=False)
    datum_updated = models.DateTimeField(auto_now=True, editable=False)
    
    def __str__(self):
        return "Book: {0} / Gruppe: {1}".format(self.book, self.gruppe)
    
    class Meta:
        ordering = ['book']
        unique_together = ('book', 'gruppe')

    def save(self, *args, **kwargs):
        if self.is_active:
            Books.objects.filter(gruppe=self.gruppe).exclude(pk=self.pk).update(is_active=False)
        try:
            neu = Books.objects.get(pk=self.pk)
            if neu.slug == '':
                neu.slug = slugify(neu.book)
            orig = new = neu.slug
            for x in itertools.count(1):
                if not Books.objects.filter(gruppe=self.gruppe).filter(slug=new).exclude(pk=self.pk).exists():
                    break
                new = '%s-%d' % (orig, x)
            self.slug = new
        except Books.DoesNotExist:
            # if self.pk is not None:  # nur ausführen bei neu
            if self.slug == '':
                self.slug = slugify(self.book)
            orig = new = self.slug
            for x in itertools.count(1):
                if not Books.objects.filter(gruppe=self.gruppe).filter(slug=new).exclude(pk=self.pk).exists():
                    break
                new = '%s-%d' % (orig, x)
            self.slug = new
        models.Model.save(self, *args, **kwargs)


class BooksTemp(models.Model):
    """Book where the Files (Dateien) are in"""
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    book = models.CharField(max_length=32, db_index=True)
    bookimpid = models.UUIDField()
    slug = models.SlugField(max_length=36, null=True, blank=True)
    gruppe = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, db_index=True)
    bookroot = models.CharField(max_length=256, default='', blank=True)
    directory = models.CharField(max_length=126, default='', blank=True)
    datum_xml = models.DateTimeField()
    datum_created = models.DateTimeField(auto_now_add=True, editable=False)
    # datum_updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return "Book: {0} / Gruppe: {1}".format(self.book, self.gruppe)

    class Meta:
        ordering = ['book']
        unique_together = ('book', 'gruppe')


class Dateien(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    book = models.ForeignKey('Books', on_delete=models.CASCADE, db_index=True)
    slug = models.SlugField(max_length=200)
    label = models.CharField(max_length=200, null=False, blank=False)  # original name
    dmsname = models.CharField(max_length=255, null=False, blank=False, default='')  # name in filesystem
    hinweis = models.TextField(max_length=20000, default='', blank=True)
    # content = HTMLField()
    # pdf2text; extra table as pdf is not general used ?
    # keyword = models.ForeignKey('KeyWords', on_delete=models.SET_NULL, null=True, blank=True, db_index=True)
    pfad = models.ForeignKey('Url', on_delete=models.SET_NULL, null=True, blank=True, db_index=True)
    is_active = models.BooleanField(default=False, db_index=True)
    dateiimpid = models.UUIDField(null=True, blank=True)
    datum_created = models.DateTimeField(auto_now_add=True, editable=False)
    datum_updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return "Book: {0} / Datei: {1}".format(self.book, self.label)

    class Meta:
        unique_together = ('book', 'slug')  # für den Import
        ordering = ['label']  # ordering = ['book', 'label']
        verbose_name = 'Datei'
        verbose_name_plural = 'Dateien'

    def save(self, *args, **kwargs):
        # if self.pk is not None:  # muss immer ausgeführt werden
        if self.slug == '':
            self.slug = slugify(self.label)
        orig = self.slug
        for x in itertools.count(1):
            if not Dateien.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
                break
            self.slug = '%s-%d' % (orig, x)
        # je Book soll / darf nur eine Notiz aktiv sein
        if self.is_active:
            if not Dateien.objects.get(pk=self.pk).is_active:
                Dateien.objects.filter(book=self.book).exclude(pk=self.pk).update(is_active=False)
        models.Model.save(self, *args, **kwargs)


class Schluessel(models.Model):
    """
    Table for KeyWords = Schluessel
    """
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    book = models.ForeignKey('Books', on_delete=models.CASCADE, db_index=True)
    schluessel = models.CharField(max_length=100, db_index=True)  # unique ??
    slug = models.SlugField(max_length=200)
    schluesselimpid = models.UUIDField(null=True, blank=True)
    gruppe = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, db_index=True)
    # datei = models.ForeignKey('Dateien', on_delete=models.SET_NULL, null=True, db_index=True)
    datum_created = models.DateTimeField(auto_now_add=True, editable=False)
    datum_updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.slug

    class Meta:
        unique_together = (('gruppe', 'slug'), ('gruppe', 'schluessel'))

    def save(self, *args, **kwargs):
        # if self.pk is not None:  # muss immer ausgeführt werden
        orig = self.schluessel
        for x in itertools.count(1):
            if not Schluessel.objects.filter(gruppe=self.gruppe).filter(schluessel=self.schluessel).exclude(
                    pk=self.pk).exists():
                break
            self.schluessel = '%s-%d' % (orig, x)
        if self.slug == '':
            self.slug = slugify(self.schluessel)
        orig = self.slug
        for x in itertools.count(1):
            if not Schluessel.objects.filter(gruppe=self.gruppe).filter(slug=self.slug).exclude(pk=self.pk).exists():
                break
            self.slug = '%s-%d' % (orig, x)
        models.Model.save(self, *args, **kwargs)


class Schluessel2Datei(models.Model):
    """
    Tabelle connects Schluessel (KeyWord) to Datei
    """
    datei = models.ForeignKey('Dateien', on_delete=models.CASCADE)
    schluessel = models.ForeignKey('Schluessel', on_delete=models.CASCADE)


class Url(models.Model):
    """ URL (Tree path zu slug """
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    book = models.ForeignKey('Books', on_delete=models.CASCADE, db_index=True)
    slug = models.CharField(max_length=255, db_index=True)  # , unique=True)
    pfad = models.CharField(max_length=255)  # , unique=True)  # mit Book
    ebene = models.PositiveIntegerField(default=0, db_index=True)  # Tree Ebene
    auf = models.PositiveIntegerField(default=0, db_index=True)  # default=1 könnte alles einblenden
    parent = models.CharField(max_length=255, db_index=True, blank=True)  # muss den slug des parents enthalten
    urlimpid = models.UUIDField(null=True, blank=True)
    filesubpath = models.CharField(max_length=255, db_index=True, blank=True, default='')
    datum_created = models.DateTimeField(auto_now_add=True, editable=False)
    datum_updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        # return "{0}".format(self.slug)  # , self.path)
        return self.slug

    class Meta:
        ordering = ['book', 'pfad']
        unique_together = (('book', 'slug'), ('book', 'pfad'))

    def save(self, *args, **kwargs):
        if self.slug == '':
            self.slug = slugify(self.pfad)
        orig = self.slug
        for x in itertools.count(1):
            if not Url.objects.filter(book=self.book).filter(slug=self.slug).exclude(pk=self.pk).exists():
                break
            self.slug = '%s-%d' % (orig, x)
        models.Model.save(self, *args, **kwargs)

webdms/wspath/models.py
from django.db import models

# Create your models here.

webdms/forms.py
from django import forms
from .models import Books, Schluessel, Url
from django.utils.text import slugify
import itertools


class BooksForm(forms.ModelForm):
    class Meta:
        model = Books
        exclude = ('date_created', 'date_updated')

    def __init__(self, **kwargs):
        self.__user = kwargs.pop('user', None)
        super(BooksForm, self).__init__(**kwargs)

    def save(self, commit=True):
        if self.instance.pk is None:
            if self.__user is None:
                raise TypeError("You didn't give an user argument to the constructor.")
            self.instance.slug = slugify(self.instance.label)
            self.instance.author = self.__user
        return super(BooksForm, self).save(commit)


class SchluesselForm(forms.ModelForm):
    class Meta:
        model = Schluessel
        exclude = ('date_created', 'date_updated')

    def __init__(self, **kwargs):
        self.__user = kwargs.pop('user', None)
        super(SchluesselForm, self).__init__(**kwargs)

    def save(self, commit=True):
        if self.instance.pk is None:
            if self.__user is None:
                raise TypeError("You didn't give an user argument to the constructor.")
            self.instance.slug = slugify(self.instance.keyword)
            self.instance.author = self.__user
        return super(SchluesselForm, self).save(commit)


class UrlForm(forms.ModelForm):
    class Meta:
        model = Url
        exclude = ('date_created', 'date_updated')

    def __init__(self, **kwargs):
        # def __init__(self, *args, **kwargs):
        # if kwargs['instance'] is not None:
        try:
            if Url.objects.filter(book=kwargs['data']['book']).filter(slug=kwargs['data']['slug']).exists():
                orig = kwslug = kwargs['data']['slug']
                if '-1' in kwslug:
                    position = kwslug.index('-1')
                    orig = kwslug[:position]
                for x in itertools.count(1):
                    if not Url.objects.filter(slug=kwslug).exists():
                        break
                    kwslug = '%s-%d' % (orig, x)
                kwargs['data']['slug'] = kwslug
        except KeyError:
            pass
        self.__user = kwargs.pop('user', None)
        super(UrlForm, self).__init__(**kwargs)

    def save(self, commit=True):
        if self.instance.pk is None:
            if self.__user is None:
                raise TypeError("You didn't give an user argument to the constructor.")
            self.instance.slug = slugify(self.instance.child)
            self.instance.author = self.__user
        return super(UrlForm, self).save(commit)


def validate_file_7z(value):
    if not value.name.lower().endswith('.7z'):
        raise forms.ValidationError("Es können nur 7z-Dateien eingelesen werden.")


class UploadFileFormWeb7z(forms.Form):
    # title = forms.CharField(max_length=250)
    file = forms.FileField(label='Bitte eine 7z-Datei auswählen', validators=[validate_file_7z])

webdms/templates/books_mediabackup.html
{% extends 'basicbase.html' %}

{% block title %}Restore{% endblock %}

{% block content %}
    {% include "viewmedia_backup.html" %}
{% endblock content %}

webdms/templates/schluesselfound.html
{% extends 'basicbase.html' %}

{% block title %}KeyWords{% endblock %}

{% block content %}
    {% include "viewschluesselfound_page.html" %}
{% endblock content %}

webdms/templates/viewbooks_page.html
{% load templatetag %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4"></div>

    <!-- Content Row -->
    <div class="row">
        <!-- Content Link-Menü -->
        <div class="col-lg-2 mb-4">
            <div class="row">
                <div class="col-lg-12 mb-4">
                    <div class="list-group">
                        {% for label in notelist %}
                            {% if label.slug == notiz.slug %}
                                <a href="{% url 'webdms:noteview' treeslug label.slug %}"
                                   class="list-group-item list-group-item-action list-group-item-warning">{{ label.label }}</a>
                            {% else %}
                                <a href="{% url 'webdms:noteview' treeslug label.slug %}"
                                   class="list-group-item list-group-item-action list-group-item-info">{{ label.label }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                <div class="col-lg-6 mb-4">
                    <div class="card bg-info text-white shadow">
                        <a href="{% url 'webdms:bookadd' %}">
                            <div class="card-body">
                                Neues Buch anlegen
                                {#                      <div class="text-white-50 small">#1cc88a</div>#}
                            </div>
                        </a>
                    </div>
                    <br/>
                    <div class="card bg-info text-white shadow">
                        <a href="{% url 'webdms:menu' %}"><div class="card-body">Menü anlegen</div></a>
                    </div>
                </div>
            </div>
        </div>
        <!-- Content Link-Menü Ende-->

        <!-- Content Text -->
        <div class="col-lg-10 mb-4">

            <!-- Approach -->
            <div class="row">
                <div class='col-lg-4 bg-info text-white table-bordered'>Book</div>
                <div class='col-lg-1 bg-info text-white table-bordered'>Urls</div>
                <div class='col-lg-1 bg-info text-white table-bordered'>Dateien</div>
                <div class='col-lg-1 bg-info text-white table-bordered'>KeyWords</div>
                <div class='col-lg-2 bg-info text-white table-bordered'>Gruppe</div>
                <div class='col-lg-2 bg-info text-white table-bordered'>Aktiv</div>
            </div>
            {% for book in booklist %}
            <div class="row {% cycle 'bg-gray-100' 'bg-gray-200' %}">
                <div class='col-lg-4'><a href="{% url 'webdms:bookedit' book.slug %}">{{ book.book }}</a></div>
                <div class='col-lg-1'>{{ book|counturl }}</div>
                <div class='col-lg-1'>{{ book|countdateien }}</div>
                <div class='col-lg-1'>{{ book|countbookschluessel }}</div>
                <div class='col-lg-2'>{{ book.gruppe }}</div>
                <div class='col-lg-2'>{{ book.is_active }}</div>
            </div>
            {% endfor %}
            {% if addbook %}
                <form action="" method="post">{% csrf_token %}
                <div class="row">
                    <div class='col-lg-4 table-bordered'>
                        <label for="id_book" hidden="hidden">Book</label>
                        <input type="text" class="form-control" name="book" id="id_book" value="{% if object %}{{ object.book }}{% endif %}" />
                    </div>
                    <div class='col-lg-1 table-bordered'>
                        <label for="id_counttree" hidden="hidden">Url</label>
                        <input type="text" class="form-control" name="counttree" id="id_counttree" value="0" readonly /></div>
                    <div class='col-lg-1 table-bordered'>
                        <label for="id_countnote" hidden="hidden">Datei</label>
                        <input type="text" class="form-control" name="countnote" id="id_countnote" value="0" readonly /></div>
                    <div class='col-lg-1 table-bordered'>
                        <label for="id_countkeyword" hidden="hidden">Schluessel</label>
                        <input type="text" class="form-control" name="countkeyword" id="id_countkeyword" value="0" readonly /></div>
                    <div class='col-lg-2 table-bordered'>
                        <label for="id_gruppe" hidden="hidden">Gruppe</label>
                        <input type="text" class="form-control" name="gruppe" id="id_gruppe" value="{{ mygruppe }}" readonly />
                    </div>
                    <div class='col-lg-2 table-bordered'>
                        <label for="id_is_active" hidden="hidden">Aktiv</label>
                        <input type="text" class="form-control" name="is_active" id="id_is_active" value="False" readonly />
                    </div>
                </div>
                <br />
                <div class="row">
                    <div class='col-lg-4'>
                        {% if object %}
                            <input type='submit' value='Save Book' name="subbook" class='btn btn-success btn-lg btn-block' />
                        {% else %}
                            <input type='submit' value='Create New Book' name="subbook" class='btn btn-success btn-lg btn-block' />
                        {% endif %}
                    </div>
                    <div class='col-lg-2'>&nbsp;</div>
                    <div class='col-lg-2'>
                        {% if object %}
                            <input type='submit' value='Remove Book' name="subbook" class='btn btn-danger btn-lg btn-block' />
                        {% endif %}
                    </div>
                </div>
                </form>
            {% endif %}
        </div>

    </div>
    <!-- Content Text Ende-->
</div>

webdms/templates/viewbookstemp_page.html
{% load babel %}
{% load templatetag %}
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4"></div>

    <!-- Content Row -->
    <div class="row">
        <!-- Content Link-Menü -->
        <div class="col-lg-2 mb-4">
            <div class="row">
                <div class="col-lg-12 mb-4">
                    <div class="list-group">
                        {% for label in notelist %}
                            {% if label.slug == notiz.slug %}
                                <a href="{% url 'webdms:noteview' treeslug label.slug %}"
                                   class="list-group-item list-group-item-action list-group-item-warning">{{ label.label }}</a>
                            {% else %}
                                <a href="{% url 'webdms:noteview' treeslug label.slug %}"
                                   class="list-group-item list-group-item-action list-group-item-info">{{ label.label }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                </div>
                {% comment %}                <div class="col-lg-6 mb-4">
                  <div class="card bg-success text-white shadow">
                    <div class="card-body">
                      Success
                      <div class="text-white-50 small">#1cc88a</div>
                    </div>
                  </div>
                </div>{% endcomment %}
            </div>
        </div>
        <!-- Content Link-Menü Ende-->


        <!-- Content Text -->
        <div class="col-lg-10 mb-4">

            <!-- Approach -->
            <form action="{% url 'webdms:bookrestore' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
                {% if form.errors %}
                    <div class="row"> <div class='col-lg-4'>{{ form.errors }}</div></div>
                {% endif %}
{#                 <div class="row">#}
{#                     <div class='col-lg-4'>#}
{#                        <label for="exampleInputFile">Datei auswählen</label>#}
{#                        <input type="file" id="id_file" name="file">#}
{#                        <p class="help-block">Books einlesen / wieder herstellen.</p>#}
{#                     </div>#}
{#                 </div>#}
                <div class="row">
                    <div class='col-lg-3 bg-info text-white table-bordered'>Book</div>
                    <div class='col-lg-2 bg-info text-white table-bordered'>Datum</div>
{#                    <div class='col-lg-1 bg-info text-white table-bordered'>Trees</div>#}
                    <div class='col-lg-1 bg-info text-white table-bordered'>Url</div>
                    <div class='col-lg-1 bg-info text-white table-bordered'>Notes</div>
                    <div class='col-lg-1 bg-info text-white table-bordered'>KeyWords</div>
                    <div class='col-lg-1 bg-info text-white table-bordered'>Neu</div>
                    <div class='col-lg-1 bg-info text-white table-bordered'>Ersetzen</div>
                    <div class='col-lg-1 bg-info text-white table-bordered'>Zusammen</div>
                </div>
            {% for book in restorelist %}
            <div class="row {% cycle 'bg-gray-100' 'bg-gray-200' %}">
                <div class='col-lg-3'>{{ book.book }}</div>
                <div class='col-lg-2'>{{ book.datum_xml|datetimefmt:"short" }}</div>
{#                <div class='col-lg-1'>{{ book.trees }}</div>#}
                <div class='col-lg-1'>{{ book.urlpaths }}</div>
                <div class='col-lg-1'>{{ book.notes }}</div>
                <div class='col-lg-1'>{{ book.keywords }}</div>
                {% if book|vorhanden %}
                    <div class='col-lg-1'>
                        <label class="control-label" for="id_books-neu__{{ forloop.counter0 }}" hidden>Books:</label>
                        <input type="checkbox" class="form-control" name="books-neu__{{ forloop.counter0 }}" id="id_books-neu__{{ forloop.counter0 }}" value="{{ book.pk }}" disabled />
                    </div>
{#                    <fieldset>#}
                    <div class='col-lg-1'>
                        <label class="control-label" for="id_books-vorhanden__{{ forloop.counter0 }}" hidden>Books:</label>
{#                        <input type="radio" class="form-control" name="books-ersetzen__{{ forloop.counter0 }}" id="id_books-ersetzen__{{ forloop.counter0 }}" value="{{ book.pk }}" />#}
                        <input type="radio" class="form-control" name="books-vorhanden__{{ forloop.counter0 }}" id="id_books-vorhanden__{{ forloop.counter0 }}" value="E___{{ book.pk }}" />
                    </div>
                    <div class='col-lg-1'>
                        <label class="control-label" for="id_books-vorhanden__{{ forloop.counter0 }}" hidden>Books:</label>
                        <input type="radio" class="form-control" name="books-vorhanden__{{ forloop.counter0 }}" id="id_books-vorhanden__{{ forloop.counter0 }}" value="Z___{{ book.pk }}" />
                    </div>
{#                    </fieldset>#}
                {% else %}
                    <div class='col-lg-1'>
                        <label class="control-label" for="id_books-neu__{{ forloop.counter0 }}" hidden>Books:</label>
                        <input type="checkbox" class="form-control" name="books-neu__{{ forloop.counter0 }}" id="id_books-neu__{{ forloop.counter0 }}" value="{{ book.pk }}" />
                    </div>
                    <div class='col-lg-1'>
                        <label class="control-label" for="id_books-ersetzen__{{ forloop.counter0 }}" hidden>Books:</label>
                        <input type="radio" class="form-control" name="books-vorhanden__{{ forloop.counter0 }}" id="id_books-ersetzen__{{ forloop.counter0 }}" value="{{ book.pk }}" disabled />
                    </div>
                    <div class='col-lg-1'>
                        <label class="control-label" for="id_books-zusammen__{{ forloop.counter0 }}" hidden>Books:</label>
                        <input type="radio" class="form-control" name="books-vorhanden__{{ forloop.counter0 }}" id="id_books-zusammen__{{ forloop.counter0 }}" value="{{ book.pk }}" disabled />
                    </div>
                {% endif %}
            </div>
            {% endfor %}
                <div class="card-header py-3">
                    <div class="row">
                        <div class="col-lg-6"><input type='submit' value='Restore Starten' name="command" class='btn btn-warning btn-lg btn-block'/></div></div></div>
            </form>
            <div class="row">
                <div class='col-lg-4'>&nbsp;</div>
                <div class='col-lg-3'></div>
            </div>

        </div>

    </div>
    <!-- Content Text Ende-->
</div>