django_start/urls.py
from django.contrib import admin
from django.urls import include, path

from basic import views
from basic import views_login
from basic.views_fehler import error_500, error_404

from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('', views.start, name='start'),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('login/', views_login.basic_login, name='mysite_basic_login'),
    path('logout/', views_login.basic_logout, name='mysite_basic_logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(template_name='basic/password_change_form.html'),
         name='mysite_basic_change'),
    path('accounts/password_change_done/',
         PasswordChangeDoneView.as_view(template_name='basic/password_change_done.html'), name='password_change_done'),
    path('start/', views.startpage, name='mysite_startpage'),
    path('end/', views.logoutpage, name='mysite_logoutpage'),
    path('error/', views.errorpage, name='mysite_errorpage'),
    path('edms/', include('dmsapp.urls', namespace='dms')),
    path('webdms/', include('webdms.urls', namespace='web_scribble_notes')),
]

handler404 = error_404
handler500 = error_500

dmsapp/urls.py
from django.urls import path
from .views import file_import, datei_download

app_name = 'dms'

# dms
urlpatterns = [
    path('datei/<str:pathslug>/<str:dateislug>', datei_download, name='dateidownload'),
    path('fileimport/<slug:treeslug>', file_import, name='fileimport'),
]

webdms/wspath/urls.py
from django.urls import path
from .path import path_view, path_datei, path_dateichange, datei_add, path_empty, path_dateiempty, \
    path_delete, path_alle, path_tree, searchsl_view
app_name = 'notes_path'


# webdms:path:datei
urlpatterns = [
    # 'webdms/path/' ...
    path('add/<str:pathslug>/', datei_add, name='add'),
    path('alle/', path_alle, name='alle'),
    path('empty/', path_empty, name='empty'),
    path('datei/<str:pathslug>/<slug:dateislug>/', path_datei, name='datei'),
    path('view/<str:pathslug>/', path_view, name='view'),
    path('change/<slug:dateislug>/', path_dateichange, name='notechange'),
    path('delete/<slug:dateislug>/', path_delete, name='delete'),
    path('dateiempty/<slug:dateislug>/', path_dateiempty, name='dateiempty'),
    path('suchen/<str:pathslug>/', searchsl_view, name='searchsl'),
    path('tree/<str:pathslug>/', path_tree, name='treechange'),
]

webdms/models.py
from django.db import models
from django.contrib.auth.models import Group
# from django.contrib.auth.models import User, Permission  # für Lokale Userverwaltung
from django.utils.text import slugify
# from django.conf import settings
# from tinymce.models import HTMLField
from uuid import uuid4
import itertools


class Books(models.Model):
    """Book where the Files (Dateien) are in"""
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    book = models.CharField(max_length=32, db_index=True)
    slug = models.SlugField(max_length=36, null=True, blank=True)
    gruppe = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, db_index=True)
    is_active = models.BooleanField(default=False)
    bookroot = models.CharField(max_length=256, default='', blank=True)
    directory = models.CharField(max_length=126, default='', blank=True)
    datum_created = models.DateTimeField(auto_now_add=True, editable=False)
    datum_updated = models.DateTimeField(auto_now=True, editable=False)
    
    def __str__(self):
        return "Book: {0} / Gruppe: {1}".format(self.book, self.gruppe)
    
    class Meta:
        ordering = ['book']
        unique_together = ('book', 'gruppe')

    def save(self, *args, **kwargs):
        if self.is_active:
            Books.objects.filter(gruppe=self.gruppe).exclude(pk=self.pk).update(is_active=False)
        try:
            neu = Books.objects.get(pk=self.pk)
            if neu.slug == '':
                neu.slug = slugify(neu.book)
            orig = new = neu.slug
            for x in itertools.count(1):
                if not Books.objects.filter(gruppe=self.gruppe).filter(slug=new).exclude(pk=self.pk).exists():
                    break
                new = '%s-%d' % (orig, x)
            self.slug = new
        except Books.DoesNotExist:
            # if self.pk is not None:  # nur ausführen bei neu
            if self.slug == '':
                self.slug = slugify(self.book)
            orig = new = self.slug
            for x in itertools.count(1):
                if not Books.objects.filter(gruppe=self.gruppe).filter(slug=new).exclude(pk=self.pk).exists():
                    break
                new = '%s-%d' % (orig, x)
            self.slug = new
        models.Model.save(self, *args, **kwargs)


class BooksTemp(models.Model):
    """Book where the Files (Dateien) are in"""
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    book = models.CharField(max_length=32, db_index=True)
    bookimpid = models.UUIDField()
    slug = models.SlugField(max_length=36, null=True, blank=True)
    gruppe = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, db_index=True)
    bookroot = models.CharField(max_length=256, default='', blank=True)
    directory = models.CharField(max_length=126, default='', blank=True)
    datum_xml = models.DateTimeField()
    datum_created = models.DateTimeField(auto_now_add=True, editable=False)
    # datum_updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return "Book: {0} / Gruppe: {1}".format(self.book, self.gruppe)

    class Meta:
        ordering = ['book']
        unique_together = ('book', 'gruppe')


class Dateien(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    book = models.ForeignKey('Books', on_delete=models.CASCADE, db_index=True)
    slug = models.SlugField(max_length=200)
    label = models.CharField(max_length=200, null=False, blank=False)  # original name
    dmsname = models.CharField(max_length=255, null=False, blank=False, default='')  # name in filesystem
    hinweis = models.TextField(max_length=20000, default='', blank=True)
    # content = HTMLField()
    # pdf2text; extra table as pdf is not general used ?
    # keyword = models.ForeignKey('KeyWords', on_delete=models.SET_NULL, null=True, blank=True, db_index=True)
    pfad = models.ForeignKey('Url', on_delete=models.SET_NULL, null=True, blank=True, db_index=True)
    is_active = models.BooleanField(default=False, db_index=True)
    dateiimpid = models.UUIDField(null=True, blank=True)
    datum_created = models.DateTimeField(auto_now_add=True, editable=False)
    datum_updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return "Book: {0} / Datei: {1}".format(self.book, self.label)

    class Meta:
        unique_together = ('book', 'slug')  # für den Import
        ordering = ['label']  # ordering = ['book', 'label']
        verbose_name = 'Datei'
        verbose_name_plural = 'Dateien'

    def save(self, *args, **kwargs):
        # if self.pk is not None:  # muss immer ausgeführt werden
        if self.slug == '':
            self.slug = slugify(self.label)
        orig = self.slug
        for x in itertools.count(1):
            if not Dateien.objects.filter(slug=self.slug).exclude(pk=self.pk).exists():
                break
            self.slug = '%s-%d' % (orig, x)
        # je Book soll / darf nur eine Notiz aktiv sein
        if self.is_active:
            if not Dateien.objects.get(pk=self.pk).is_active:
                Dateien.objects.filter(book=self.book).exclude(pk=self.pk).update(is_active=False)
        models.Model.save(self, *args, **kwargs)


class Schluessel(models.Model):
    """
    Table for KeyWords = Schluessel
    """
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    book = models.ForeignKey('Books', on_delete=models.CASCADE, db_index=True)
    schluessel = models.CharField(max_length=100, db_index=True)  # unique ??
    slug = models.SlugField(max_length=200)
    schluesselimpid = models.UUIDField(null=True, blank=True)
    gruppe = models.ForeignKey(Group, on_delete=models.CASCADE, null=True, db_index=True)
    # datei = models.ForeignKey('Dateien', on_delete=models.SET_NULL, null=True, db_index=True)
    datum_created = models.DateTimeField(auto_now_add=True, editable=False)
    datum_updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        return self.slug

    class Meta:
        unique_together = (('gruppe', 'slug'), ('gruppe', 'schluessel'))

    def save(self, *args, **kwargs):
        # if self.pk is not None:  # muss immer ausgeführt werden
        orig = self.schluessel
        for x in itertools.count(1):
            if not Schluessel.objects.filter(gruppe=self.gruppe).filter(schluessel=self.schluessel).exclude(
                    pk=self.pk).exists():
                break
            self.schluessel = '%s-%d' % (orig, x)
        if self.slug == '':
            self.slug = slugify(self.schluessel)
        orig = self.slug
        for x in itertools.count(1):
            if not Schluessel.objects.filter(gruppe=self.gruppe).filter(slug=self.slug).exclude(pk=self.pk).exists():
                break
            self.slug = '%s-%d' % (orig, x)
        models.Model.save(self, *args, **kwargs)


class Schluessel2Datei(models.Model):
    """
    Tabelle connects Schluessel (KeyWord) to Datei
    """
    datei = models.ForeignKey('Dateien', on_delete=models.CASCADE)
    schluessel = models.ForeignKey('Schluessel', on_delete=models.CASCADE)


class Url(models.Model):
    """ URL (Tree path zu slug """
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    book = models.ForeignKey('Books', on_delete=models.CASCADE, db_index=True)
    slug = models.CharField(max_length=255, db_index=True)  # , unique=True)
    pfad = models.CharField(max_length=255)  # , unique=True)  # mit Book
    ebene = models.PositiveIntegerField(default=0, db_index=True)  # Tree Ebene
    auf = models.PositiveIntegerField(default=0, db_index=True)  # default=1 könnte alles einblenden
    parent = models.CharField(max_length=255, db_index=True, blank=True)  # muss den slug des parents enthalten
    urlimpid = models.UUIDField(null=True, blank=True)
    filesubpath = models.CharField(max_length=255, db_index=True, blank=True, default='')
    datum_created = models.DateTimeField(auto_now_add=True, editable=False)
    datum_updated = models.DateTimeField(auto_now=True, editable=False)

    def __str__(self):
        # return "{0}".format(self.slug)  # , self.path)
        return self.slug

    class Meta:
        ordering = ['book', 'pfad']
        unique_together = (('book', 'slug'), ('book', 'pfad'))

    def save(self, *args, **kwargs):
        if self.slug == '':
            self.slug = slugify(self.pfad)
        orig = self.slug
        for x in itertools.count(1):
            if not Url.objects.filter(book=self.book).filter(slug=self.slug).exclude(pk=self.pk).exists():
                break
            self.slug = '%s-%d' % (orig, x)
        models.Model.save(self, *args, **kwargs)

webdms/wspath/models.py
from django.db import models

# Create your models here.

dmsapp/forms.py
from django import forms
from django.utils.text import slugify


def validate_file_all(value):
    # if not value.name.lower().endswith('.xml'):
    #     raise forms.ValidationError("Es können nur XML-Dateien eingelesen werden.")
    pass


class UploadFileFormFile(forms.Form):
    # title = forms.CharField(max_length=250)
    file = forms.FileField(label='Bitte eine Datei auswählen', validators=[validate_file_all])

webdms/wspath/templates/wspath/datei_add_form.html
{% extends 'basicbase.html' %}

{% block title %}DMS{% endblock %}

{% block content %}
    {% include "wspath/viewcontent_path.html" %}
{% endblock content %}

webdms/wspath/templates/wspath/notes_import.html
{% extends 'basicbase.html' %}

{% block title %}Notizen importieren{% endblock %}

{% block content %}
    {% include "viewimport_page.html" %}
{% endblock content %}

webdms/wspath/templates/wspath/path.html
{% extends 'basicbase.html' %}

{% block title %}Path{% endblock %}

{% block content %}
    {% include "wspath/viewcontent_path.html" %}
{% endblock content %}

webdms/wspath/templates/wspath/path_empty.html
{% extends 'basicbase.html' %}

{% block title %}ohne Tree{% endblock %}

{% block content %}
    {% include "wspath/viewcontent_page_pathempty.html" %}
{% endblock content %}

webdms/wspath/templates/wspath/viewcontent_page_pathempty.html
<div class="container-fluid">

          <!-- Page Heading -->
          <div class="d-sm-flex align-items-center justify-content-between mb-4">
          </div>

        <!-- Content Row -->
          <div class="row">
            <!-- Content Link-Menü -->
            <div class="col-lg-4 mb-4">
              <div class="row">
                <div class="col-lg-12 mb-4">
                    <div class="list-group zeigemax">
                        {% for dtlb in notelist %}
                            {% if dtlb.slug == notiz.slug %}
                                <a href="{% url 'webdms:path:dateiempty' dtlb.slug %}" class="list-group-item list-group-item-action list-group-item-warning" title="{{ dtlb.label }}">{{ dtlb.label }}</a>
                            {% else %}
                                <a href="{% url 'webdms:path:dateiempty' dtlb.slug %}" class="list-group-item list-group-item-action list-group-item-info" title="{{ dtlb.label }}">{{ dtlb.label }}</a>
                            {% endif %}
                        {% endfor %}
                    </div>
                  </div>
              </div>
            </div>
            <!-- Content Link-Menü Ende-->


            <!-- Content Text -->
            <div class="col-lg-8 mb-4">
            <!-- Approach -->
            {% if addnotiz %}
                <form action="{{ urlaction }}" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="card-header py-3">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="row"><div class="col-lg-12">
                                    <label class="control-label" for="id_pfad">Pfad unbekannt, vermutlich existiert die Datei nicht mehr</label>
                                    <select class="custom-select" id="id_pfad" name="pfad">
                                        <option value="None">-- -- -- -- -- -- --</option>
                                        {% for urlpa in pathlist %}
                                            <option value="{{ urlpa.pk }}"{% if urlpa.pk == urlid %} selected{% endif %} title="{{ urlpa.slug }}">{{ urlpa.book.book }}/{{ urlpa.pfad }}</option>
                                        {% endfor %}
                                    </select>
                                </div></div>
                                <br />
                                <div class="row"><div class="col-lg-12">
                                    {% if datei %}
{#                                    <a href="{% url 'dms:dateidownload' datei.pfad.slug datei.slug %}">#}
                                    <a href="#">
                                    <label class="control-label" for="id_label">DMSname: {{ datei.dmsname }}</label>
                                    <input type="text" class="form-control" name="label" id="id_label" value="{{ datei.label }}" readonly/></a>
                                    <br />
                                    <label class="control-label" for="id_hinweis">Hinweis</label>
                                    <input type="text" class="form-control" name="hinweis" id="id_hinweis" value="{{ datei.hinweis }}" />
                                {% else %}
                                    <p class="help-block">Neue Datei in DMS einfügen.</p>
                                    <label for="exampleInputFile">Datei auswählen</label>
                                    <input type="file" id="id_file" name="file">
                                    <label class="control-label" for="id_label" hidden>Dateiname</label>
                                    <input type="text" class="form-control" name="label" id="id_label" value="" hidden />
                                    <br />
                                    <label class="control-label" for="id_hinweis">Hinweis</label>
                                    <input type="text" class="form-control" name="hinweis" id="id_hinweis" value="" />
                                {% endif %}
                                </div></div>
{#                                <div class="row"><div class="col-lg-12">#}
{#                                </div></div>    #}
                                <br />
                                <div class="row">
                                    <div class='col-lg-4'>&nbsp;</div>
                                    <div class='col-lg-3'>
                                        {# {{form|crispy}}#}
                                        <input type='submit' value='Speichern' class='btn btn-success btn-lg btn-block'/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                {% for key in schluessellist %}
                                    <div class="row table-bordered">
                                        <div class="col-lg-3">
                                            <label class="control-label" for="{{ key.id }}" hidden>q</label>
                                            <input type="checkbox" class="form-control" name="kwschluessel__{{ key.id }}" id="{{ key.id }}"{% if key in usedschluessellist %} checked="checked"{% endif %} value="{{ key.pk }}" />
                                        </div>
                                        <div class="col-lg-9">{{ key.schluessel }}</div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                </form>
            {% elif loeschen %}
                <form action="" method="post">{% csrf_token %}
                    <div class="card-header py-3">
                        <label class="control-label text-danger" for="id_label">Notiz wirklich löschen ?</label>
                        <input type="text" class="form-control" name="label" id="id_label" value="{{ loeschen.label }}" readonly />
                    </div>
                    <label for="id_content" hidden>Conten löschen</label>
                    <input type="text" class="form-control" name="content" id="id_content" value="Content löschen"
                           hidden/>
                    <div class="card-body content-markdown">{{ loeschen.content }}</div>
                    <div class="row">
                        <div class='col-lg-4'>&nbsp;</div>
                        <div class='col-lg-3'>
                            {#                                <form action="" method="post">{% csrf_token %}#}
                            {#                                {{form|crispy}}#}
                            {% if tree %}
                                <input type='submit' value='Save Note' class='btn btn-success btn-lg btn-block'/>
                            {% elif loeschen %}
                                <input type='submit' value='Remove File' class='btn btn-danger btn-lg btn-block'/>
                            {% else %}
                                <input type='submit' value='Create New Note!' class='btn btn-success btn-lg btn-block'/>
                            {% endif %}
                            {#                                </form>#}
                        </div>
                    </div>
                </form>
            {% elif notiz %}
                <div class="card-header py-3">
                    <div class="row">
                        <div class='col-lg-8'>
                            <h6 class="m-0 font-weight-bold text-primary">
                            <a href="{% url 'webdms:path:notechange' notiz.slug %}" title="bearbeiten">
                                <i class="fas fa-fw fa-wrench"></i> {{ notiz.label }}</a></h6>
                        </div>
                        <div class='col-lg-4'>{{ notiz.keyword.keyword }}</div>
                    </div>
                </div>
                <div class="card-body">
                    {% for datei in beleglist %}
                        <a href="#">{{ datei.originalname }}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
            </div>
            <!-- Content Text Ende-->
</div>

webdms/wspath/templates/wspath/viewcontent_path.html
<div class="container-fluid">

    <!-- Page Heading -->
    <div class="d-sm-flex align-items-center justify-content-between mb-4">
    </div>

    <!-- Content Row -->
    <div class="row">
        <!-- Content Link-Menü -->
        <div class="col-lg-4 mb-4">
            <div class="row">
                <div class="col-lg-12 mb-4">
                    <div class="list-group zeigemax">
                        {% for datei in dateilist %}
                            <a href="{% url 'webdms:path:datei' pathslug datei.slug %}" class="list-group-item list-group-item-action list-group-item-warning" title="{{ datei.label }}">{{ datei.label }}</a>
                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <!-- Content Link-Menü Ende-->

        <!-- Content Text -->
        <div class="col-lg-8 mb-4">
            <!-- Approach -->
            {% if addnotiz %}
                <form action="{{ urlaction }}" method="post" enctype="multipart/form-data">{% csrf_token %}
                    <div class="card-header py-3">
                        <div class="row">
                            <div class="col-lg-8">
                                <div class="row"><div class="col-lg-12">
                                    <label class="control-label" for="id_pfad">Pfad</label>
                                    <select class="custom-select" id="id_pfad" name="pfad">
                                        <option value="None">-- -- -- -- -- -- --</option>
                                        {% for urlpa in pathlist %}{# {% for urlpa in urllist %} #}
                                            <option value="{{ urlpa.pk }}"{% if urlpa.pk == urlid %} selected{% endif %} title="{{ urlpa.slug }}">{{ urlpa.book.book }}/{{ urlpa.pfad }}</option>
                                        {% endfor %}
                                    </select>
                                </div></div>
                                <br />
                                <div class="row"><div class="col-lg-12">
                                    {% if datei %}
                                    <a href="{% url 'dms:dateidownload' datei.pfad.slug datei.slug %}">
                                    <label class="control-label" for="id_label">Dateiname</label>
                                    <input type="text" class="form-control" name="label" id="id_label" value="{{ datei.label }}" readonly/></a>
                                    <br />
                                    <label class="control-label" for="id_hinweis">Hinweis</label>
                                    <input type="text" class="form-control" name="hinweis" id="id_hinweis" value="{{ datei.hinweis }}" />
                                {% else %}
                                    <p class="help-block">Neue Datei in DMS einfügen.</p>
                                    <label for="exampleInputFile">Datei auswählen</label>
                                    <input type="file" id="id_file" name="file">
                                    <label class="control-label" for="id_label" hidden>Dateiname</label>
                                    <input type="text" class="form-control" name="label" id="id_label" value="" hidden />
                                    <br />
                                    <label class="control-label" for="id_hinweis">Hinweis</label>
                                    <input type="text" class="form-control" name="hinweis" id="id_hinweis" value="" />
                                {% endif %}
                                </div></div>
{#                                <div class="row"><div class="col-lg-12">#}
{#                                </div></div>    #}
                                <br />
                                <div class="row">
                                    <div class='col-lg-4'>&nbsp;</div>
                                    <div class='col-lg-3'>
                                        {# {{form|crispy}}#}
                                        <input type='submit' value='Speichern' class='btn btn-success btn-lg btn-block'/>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-3">
                                {% for key in schluessellist %}
                                    <div class="row table-bordered">
                                        <div class="col-lg-3">
                                            <label class="control-label" for="{{ key.id }}" hidden>q</label>
                                            <input type="checkbox" class="form-control" name="kwschluessel__{{ key.id }}" id="{{ key.id }}"{% if key in usedschluessellist %} checked="checked"{% endif %} value="{{ key.pk }}" />
                                        </div>
                                        <div class="col-lg-9">{{ key.schluessel }}</div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>
                </form>
            {% elif loeschen %}
                <form action="" method="post">{% csrf_token %}
                    <div class="card-header py-3">
                        <label class="control-label text-danger" for="id_label">Datei wirklich löschen ?</label>
                        <input type="text" class="form-control" name="label" id="id_label" value="{{ loeschen.label }}" readonly />
                    </div>
                    <label for="id_content" hidden>Conten löschen</label>
                    <input type="text" class="form-control" name="content" id="id_content" value="Content löschen"
                           hidden/>
                    <div class="card-body content-markdown">{{ loeschen.content }}</div>
                    <div class="row">
                        <div class='col-lg-4'>&nbsp;</div>
                        <div class='col-lg-3'>
                            {#                                <form action="" method="post">{% csrf_token %}#}
                            {#                                {{form|crispy}}#}
                            {% if tree %}
                                <input type='submit' value='Save Note' class='btn btn-success btn-lg btn-block'/>
                            {% elif loeschen %}
                                <input type='submit' value='Remove File' class='btn btn-danger btn-lg btn-block'/>
                            {% else %}
                                <input type='submit' value='Create New Note!' class='btn btn-success btn-lg btn-block'/>
                            {% endif %}
                            {#                                </form>#}
                        </div>
                    </div>
                </form>
            {% elif notiz %}
                <div class="card-header py-3">
                    <div class="row">
                        <div class='col-lg-8'>
                            <h6 class="m-0 font-weight-bold text-primary">
                            <a href="{% url 'webdms:path:notechange' notiz.slug %}" title="bearbeiten">
                                <i class="fas fa-fw fa-wrench"></i> {{ notiz.label }}</a></h6>
                        </div>
                        <div class='col-lg-4'>{{ notiz.keyword.keyword }}</div>
                    </div>
                </div>
                <div class="card-body">
                    {% for datei in beleglist %}
                        <a href="#">{{ datei.originalname }}</a>
                    {% endfor %}
                </div>
            {% endif %}
        </div>
    </div>
    <!-- Content Text Ende-->
</div>