django_start/urls.py
from django.contrib import admin
from django.urls import include, path

from basic import views
from basic import views_login
from basic.views_fehler import error_500, error_404

from django.contrib.auth.views import PasswordChangeView, PasswordChangeDoneView


urlpatterns = [
    path('', views.start, name='start'),
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),
    path('login/', views_login.basic_login, name='mysite_basic_login'),
    path('logout/', views_login.basic_logout, name='mysite_basic_logout'),
    path('accounts/password_change/', PasswordChangeView.as_view(template_name='basic/password_change_form.html'),
         name='mysite_basic_change'),
    path('accounts/password_change_done/',
         PasswordChangeDoneView.as_view(template_name='basic/password_change_done.html'), name='password_change_done'),
    path('start/', views.startpage, name='mysite_startpage'),
    path('end/', views.logoutpage, name='mysite_logoutpage'),
    path('error/', views.errorpage, name='mysite_errorpage'),
    path('edms/', include('dmsapp.urls', namespace='dms')),
    path('webdms/', include('webdms.urls', namespace='web_scribble_notes')),
]

handler404 = error_404
handler500 = error_500

dmsapp/urls.py
from django.urls import path
from .views import file_import, datei_download

app_name = 'dms'

# dms
urlpatterns = [
    path('datei/<str:pathslug>/<str:dateislug>', datei_download, name='dateidownload'),
    path('fileimport/<slug:treeslug>', file_import, name='fileimport'),
]

webdms/urls.py
from django.urls import path, include
# from django.contrib import admin
from .view_book import change_book, book_view, book_add, book_edit, book_backup, book_restore, \
    book_viewtemp, book_media
from .view_keywords import schluessel_add, schluessel_edit, schluessel_find, schluessel_view, schluessel_view_notes
from .view_note import datei_view, datei_add, datei_change, note_delete, datei_fehler, datei_view_book
from .view_url import tree_error, url_change, url_add, menu_add
from .views import index_view, tree_empty, menu_view
from .view_search import search_view
app_name = 'webdms'


# webdms:
urlpatterns = [
    # 'webdms/'
    path('', index_view, name='index'),
    path('menu/', menu_view, name='menu'),
    # path('menu/<str:pathslug>/', menu_add, name='menu_add'),
    path('book/', book_view, name='bookview'),
    path('bookadd/', book_add, name='bookadd'),
    path('bookedit/<slug:bookslug>/', book_edit, name='bookedit'),
    # path('bookdelete/<slug:bookslug>/', book_delete, name='bookdelete'),
    path('bookbackup/', book_backup, name='bookbackup'),
    path('bookrestore/', book_restore, name='bookrestore'),
    path('bookmedia/<str:todo>/<str:dateiname>/', book_media, name='bookmedia'),
    path('booktemp/', book_viewtemp, name='bookviewtemp'),
    path('bookchange/<slug:bookslug>/', change_book, name='changebook'),
    path('path/', include('webdms.wspath.urls', namespace='path')),
    path('tree/<str:pfadslug>/fehlernote/<int:fehlerid>/', datei_fehler, name='notefehler'),
    path('treeadd/', url_add, name='treeadd'),
    path('treeadd/<str:pathslug>/', menu_add, name='menu_add'),
    path('treechange/', url_change, name='treechange'),  # hier wird URL gefüllt
    path('treeempty/', tree_empty, name='treeempty'),
    path('treerror/<int:error>/', tree_error, name='treeerror'),
    path('note/<slug:treeslug>/<slug:noteslug>', datei_view, name='noteview'),
    path('notebook/<slug:bookslug>/<slug:treeslug>/<slug:noteslug>', datei_view_book, name='notesviewbook'),
    path('noteadd/<slug:treeslug>', datei_add, name='noteadd'),
    path('notechange/<slug:noteslug>', datei_change, name='notechange'),
    path('notedelete/<slug:noteslug>', note_delete, name='notedelete'),
    # path('noteimport/<slug:treeslug>', note_import, name='noteimport'),
    # noch nicht fertig
    path('keywords', schluessel_view, name='keywords_view'),
    path('keywordadd', schluessel_add, name='keywordadd'),
    path('keyword/<slug:keyslug>/', schluessel_edit, name='keywordsedit'),
    path('keywordfind/<slug:keyslug>/', schluessel_find, name='schluesselfind'),
    path('keywordview/<slug:bookslug>/<slug:keyslug>/<slug:dateislug>', schluessel_view_notes, name='keywordsviewnotes'),
    path('suchen/', search_view, name='search'),
]

webdms/wspath/urls.py
from django.urls import path
from .path import path_view, path_datei, path_dateichange, datei_add, path_empty, path_dateiempty, \
    path_delete, path_alle, path_tree, searchsl_view
app_name = 'notes_path'


# webdms:path:datei
urlpatterns = [
    # 'webdms/path/' ...
    path('add/<str:pathslug>/', datei_add, name='add'),
    path('alle/', path_alle, name='alle'),
    path('empty/', path_empty, name='empty'),
    path('datei/<str:pathslug>/<slug:dateislug>/', path_datei, name='datei'),
    path('view/<str:pathslug>/', path_view, name='view'),
    path('change/<slug:dateislug>/', path_dateichange, name='notechange'),
    path('delete/<slug:dateislug>/', path_delete, name='delete'),
    path('dateiempty/<slug:dateislug>/', path_dateiempty, name='dateiempty'),
    path('suchen/<str:pathslug>/', searchsl_view, name='searchsl'),
    path('tree/<str:pathslug>/', path_tree, name='treechange'),
]

webdms/wspath/models.py
from django.db import models

# Create your models here.

webdms/forms.py
from django import forms
from .models import Books, Schluessel, Url
from django.utils.text import slugify
import itertools


class BooksForm(forms.ModelForm):
    class Meta:
        model = Books
        exclude = ('date_created', 'date_updated')

    def __init__(self, **kwargs):
        self.__user = kwargs.pop('user', None)
        super(BooksForm, self).__init__(**kwargs)

    def save(self, commit=True):
        if self.instance.pk is None:
            if self.__user is None:
                raise TypeError("You didn't give an user argument to the constructor.")
            self.instance.slug = slugify(self.instance.label)
            self.instance.author = self.__user
        return super(BooksForm, self).save(commit)


class SchluesselForm(forms.ModelForm):
    class Meta:
        model = Schluessel
        exclude = ('date_created', 'date_updated')

    def __init__(self, **kwargs):
        self.__user = kwargs.pop('user', None)
        super(SchluesselForm, self).__init__(**kwargs)

    def save(self, commit=True):
        if self.instance.pk is None:
            if self.__user is None:
                raise TypeError("You didn't give an user argument to the constructor.")
            self.instance.slug = slugify(self.instance.keyword)
            self.instance.author = self.__user
        return super(SchluesselForm, self).save(commit)


class UrlForm(forms.ModelForm):
    class Meta:
        model = Url
        exclude = ('date_created', 'date_updated')

    def __init__(self, **kwargs):
        # def __init__(self, *args, **kwargs):
        # if kwargs['instance'] is not None:
        try:
            if Url.objects.filter(book=kwargs['data']['book']).filter(slug=kwargs['data']['slug']).exists():
                orig = kwslug = kwargs['data']['slug']
                if '-1' in kwslug:
                    position = kwslug.index('-1')
                    orig = kwslug[:position]
                for x in itertools.count(1):
                    if not Url.objects.filter(slug=kwslug).exists():
                        break
                    kwslug = '%s-%d' % (orig, x)
                kwargs['data']['slug'] = kwslug
        except KeyError:
            pass
        self.__user = kwargs.pop('user', None)
        super(UrlForm, self).__init__(**kwargs)

    def save(self, commit=True):
        if self.instance.pk is None:
            if self.__user is None:
                raise TypeError("You didn't give an user argument to the constructor.")
            self.instance.slug = slugify(self.instance.child)
            self.instance.author = self.__user
        return super(UrlForm, self).save(commit)


def validate_file_7z(value):
    if not value.name.lower().endswith('.7z'):
        raise forms.ValidationError("Es können nur 7z-Dateien eingelesen werden.")


class UploadFileFormWeb7z(forms.Form):
    # title = forms.CharField(max_length=250)
    file = forms.FileField(label='Bitte eine 7z-Datei auswählen', validators=[validate_file_7z])

webdms/views.py
from django.contrib.auth.decorators import login_required
# from django.core.exceptions import
from django.http import HttpResponseRedirect
from django.shortcuts import render  # , get_object_or_404
from django.urls import reverse
# from django.utils.text import slugify
from .models import Dateien  # , Url  # , Group  Books,
# from dmsapp.models import Beleg
from basic.models import Gruppe
# from .pathurl import noteurl, belegurl
from .tools import booknavi, pfadnavi


def index_view(request):
    """
    Stertseite mit Menü auf Linker Seote
    :param request:
    :return:
    """
    if request.user.is_authenticated:
        if Gruppe.objects.filter(user=request.user).count() == 0:
            # print('Fehler - keine gruppe in request.user')
            return HttpResponseRedirect(reverse('mysite_errorpage', args=[]))
        schluessellist, booklist, prime = booknavi(request.user.gruppe.group_id)
        if not prime:
            return HttpResponseRedirect(reverse('webdms:bookview'))
        pathlist, emptylist = pfadnavi(prime)
        # emptylist = Notes.objects.filter(book=prime).exclude(tree__isnull=False)
        pathlist0 = pathlist  # .filter(ebene=0)
        # Prüfen ob es für das Book eine aktive Notiz gibt, wenn ja, dann laden
        try:
            datei = Dateien.objects.filter(book=prime).get(is_active=True)
            return HttpResponseRedirect(reverse('webdms:path:datei', args=[datei.pfad.slug, datei.slug]))
        except AttributeError:
            datei = Dateien.objects.filter(book=prime).get(is_active=True)
            datei.is_active = False
            datei.save(update_fields=['is_active'])
            return HttpResponseRedirect(reverse('webdms:index', args=[]))
        except Dateien.DoesNotExist:
            dictionary = {
                'booklist': booklist,
                'book': prime,
                'emptylist': emptylist,
                'pathlist': pathlist0,
                'schluessellist': schluessellist,
                'angemeldet': True,
                'error': False,
            }
            return render(request, 'webdms/start.html', dictionary)
    else:
        return HttpResponseRedirect(reverse('mysite_basic_login', args=[]))


@login_required
def menu_view(request):
    """
    Anzeige des Menü
    :param request:
    :return:
    """
    if Gruppe.objects.filter(user=request.user).count() == 0:
        # print('Fehler - keine gruppe in request.user')
        return HttpResponseRedirect(reverse('mysite_errorpage', args=[]))
    schluessellist, booklist, prime = booknavi(request.user.gruppe.group_id)
    if not prime:
        return HttpResponseRedirect(reverse('webdms:bookview'))
    pathlist, emptylist = pfadnavi(prime)
    # emptylist = Notes.objects.filter(book=prime).exclude(tree__isnull=False)
    pathlist0 = pathlist  # .filter(ebene=0)
    dictionary = {
        'booklist': booklist,
        'book': prime,
        'emptylist': emptylist,
        'pathlist': pathlist0,
        'schluessellist': schluessellist,
        'angemeldet': True,
        'error': False,
    }
    return render(request, 'webdms/menu.html', dictionary)


@login_required
def tree_empty(request):
    """
    Zur Anzeige von Notizen ohne Zuordnung
    :param request:
    :return:
    """
    schluessellist, booklist, prime = booknavi(request.user.gruppe.group_id)
    pathlist, emptylist = pfadnavi(prime)
    notelist = emptylist
    dictionary = {
        'booklist': booklist,
        'book': prime,
        'notelist': notelist,
        'emptylist': emptylist,
        'schluessellist': schluessellist,
        'angemeldet': True,
        'error': False,
        'treeslug': None,
    }
    return render(request, 'tree_empty.html', dictionary)

webdms/templates/webdms/_nav-item-schluessel.html
            <li class="nav-item dropdown no-arrow mx-1">
              <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="{{ keywordused }}">
{#                <i class="fas fa-bell fa-fw"></i>#}
                  {% if keywordused %}{{ keywordused }}{% else %}KeyWords{% endif %}
                <!-- Counter - Alerts -->
{#                <span class="badge badge-danger badge-counter">3+</span>#}
              </a>
              <!-- Dropdown - Alerts -->
              <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                  KeyWords
                </h6>
                  {% for key in schluessellist %}
                  <a class="dropdown-item d-flex align-items-center" href="{% url 'webdms:schluesselfind' key.slug %}">
                      <div class="mr-1"></div>{% comment %}Einrückung{% endcomment %}
                          <div>
                            <span class="font-weight-bold">{{ key.schluessel }}</span>
                          </div>
                  </a>
                  {% endfor %}

                <a class="dropdown-item text-center small text-gray-500" href="{% url 'webdms:keywords_view' %}">Show All KeyWords</a>
              </div>
            </li>

webdms/templates/webdms/menu.html
{% extends 'basicbase.html' %}

{% block title %}Menüseite{% endblock %}

{% block content %}

{% if error %}
    {% include "__error-anmeldung.html" %}
{% else %}
    {% include "__page-content.html" %}
{% endif %}

{% endblock content %}

webdms/templates/webdms/start.html
{% extends 'basicbase.html' %}

{% block title %}Startseite{% endblock %}

{% block content %}

{% if error %}
    {% include "__error-anmeldung.html" %}
{% else %}
    {% include "__page-content.html" %}
{% endif %}

{% endblock content %}

webdms/templates/webdms/toggle_books.html
<li class="nav-item dropdown no-arrow mx-5">
    <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" title="{{ book.book }}">
        <i class="fas fa-fw">{{ book.book|slice:':8' }}</i>
    </a>
    <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">Books</h6>
        {% for stk in booklist %}
        <a class="dropdown-item d-flex align-items-center{% if stk.is_active %} bg-gradient-success{% endif %}" href="{% url 'webdms:changebook' stk.slug %}">
            <div><span class="font-weight-bold">{{ stk.book }}</span></div>
        </a>
        {% endfor %}
        <a class="dropdown-item text-center small text-gray-500" href="{% url 'webdms:bookview' %}">Zeige alle Bücher</a>
    </div>
</li>

webdms/templates/webdms/toggle_new-delete_button.html
<div class="row">
    <div class="col">
        {% if pathslug %}<a href="{% url 'webdms:path:add' pathslug %}" class="icon-circle bg-primary" title="Neue Datei ablegen"><i class="fas fa-file-alt text-white"></i></a>{% endif %}
    </div>
    <div class="col">
        {% if pathslug %}
            <a href="{% url 'webdms:path:searchsl' pathslug %}" class="icon-circle bg-gradient-success" title="in Menü und Notizen suchen"><i class="fas fa-search text-white"></i></a>
        {% else %}
            <a href="{% url 'webdms:search' %}" class="icon-circle bg-gradient-success" title="in Menü und Notizen suchen"><i class="fas fa-search text-white"></i></a>
        {% endif %}
    </div>
    <div class="col">
        {% if pathslug %}<a href="{% url 'webdms:menu_add' pathslug %}" class="icon-circle bg-gradient-warning" title="Neues Untermenü anlegen"><i class="fas fa-plus text-white"></i></a>{% endif %}
    </div>
{% if datei %}
    <div class="col">
        <a href="{% url 'webdms:path:delete' datei.slug %}" class="btn btn-danger btn-circle" title="Datei löschen"><i class="fas fa-trash"></i></a>
    </div>
{% endif %}
</div>

webdms/templates/webdms/toggle_path.html
{% for pt in pathlist %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webdms:path:view' pt.slug %}"><span>{{ pt.path }}</span></a>
    </li>
{% endfor %}
<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">
{% if emptylist %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webdms:path:empty' %}"><span>Ohne Pfad</span></a>
    </li>
{% endif %}
<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">
<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

webdms/templates/webdms/toggle_path_jstree.html
{% load treebauen %}
{#<div id="jstree_demo_div">#}
<div id="jstree">
    <ul>
{#      <li>Root node 1#}
{#        <ul>#}
{#          <li id="child_node_1">Child node 1</li>#}
{#          <li>Child node 2</li>#}
{#        </ul>#}
{#      </li>#}
{#      <li>Root node 2</li>#}
      {% for pt in pathlist %}
          {% if pt.ebene == 0 %}
            {# wenn sich der Wert von pt.ebene ändert dann  #}
{#            </li><li title="{{ pt.path }}"><a href="{% url 'webdms:path:view' pt.slug %}">{{ pt.path }}</a>#}
              </li><li id="{{ pt.slug }}" title="{{ pt.path }}">{{ pt.path }}
          {% else %}
              <ul>
{#                  <li id="{{ pt.slug }}">{{ pt.path|teil }}</li>#}
                  <li id="{% url 'webdms:path:view' pt.slug %}">{{ pt.path|teil }}</li>
{#                  <li title="{{ pt.path }}">{{ pt.path|teil }}</li>#}
              </ul>
          {% endif %}
      {% endfor %}
        </li>
    </ul>
</div>
{#<button>demo button</button>#}
{% for pt in pathlist %}
    <li class="nav-item">
        <a class="nav-link" href="{% url 'webdms:path:view' pt.slug %}"><span>{{ pt.path }}</span></a>
    </li>
{% endfor %}
<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">
{% if emptylist %}
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webdms:path:empty' %}"><span>Ohne Pfad</span></a>
    </li>
{% endif %}
<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">
<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">

webdms/templates/webdms/toggle_path_static.html
{% load treebauen %}
{% for pt in pathlist %}
    {% if pt.ebene == 0 or pt.auf == 1 %}
{#        <div class="zeigemax">#}
        <li class="nav-item {% if pt.slug == urlslug %}text-info bg-info{% else %}text-primary{% endif %} zeigemax">
        {% if pt|hassub1 %}<a class="text-white" href="{% url 'webdms:path:treechange' pt.slug %}">&nbsp;+&nbsp;</a>
        {% elif pt|hassub2 %}-+-<a class="text-white" href="{% url 'webdms:path:treechange' pt.slug %}">&nbsp;+&nbsp;</a>
        {% elif pt|issub2 %}-+-+--
        {% elif pt|issub1 %}-+-
        {% else %}-{% endif %}
            <a class="text-white" href="{% url 'webdms:path:view' pt.slug %}" title="{{ pt|removeparent }}"><span>{{ pt|removeparent }}</span></a>
        </li>
{#        </div>#}
    {% endif %}
{% endfor %}
<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">
{% if emptylist %}
    <li class="nav-item text-primary">
        --<a class="text-white" href="{% url 'webdms:path:empty' %}"><span>Ohne Pfad</span></a></li>
{% endif %}

webdms/templates/webdms/toggle_tree.html
{% for tree in directlist %}
<li class="nav-item active">
    <a class="nav-link" href="{% url 'webdms:treeview' tree.slug %}">
{#    <i class="fas fa-fw fa-tachometer-alt"></i>#}
    <span>{{ tree.child }}</span></a>
</li>
{% endfor %}
<!-- Divider -->
<hr class="sidebar-divider d-none d-md-block">
      <!-- Nav Item - Utilities Collapse Menu -->
{% for tree in treelist %}
      <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapse{{ tree.child }}" aria-expanded="true" aria-controls="collapse{{ tree.child }}">
{#          <i class="fas fa-fw fa-wrench"></i>  |dictsort:"name"#}
          <span>{{ tree.child }}</span>
        </a>
        <div id="collapse{{ tree.child }}" class="collapse" aria-labelledby="heading{{ tree.child }}" data-parent="#accordionSidebar">
          <div class="bg-white py-2 collapse-inner rounded">
              {% for child in parentlist %}
                  {% if tree.child == child.parent %}
{#                      <a class="collapse-item" href="{% url 'webdms:childview' child.slug %}">{{ child.child }}</a>#}
                      <a class="collapse-item" href="{% url 'webdms:childview' child.parent child.slug %}">{{ child.child }}</a>
                  {% endif %}
              {% endfor %}
          </div>
        </div>
      </li>
{% endfor %}
{% if emptylist %}
    <hr class="sidebar-divider d-none d-md-block">
    <li class="nav-item active">
        <a class="nav-link" href="{% url 'webdms:treeempty' %}"><span>Ohne Tree</span></a>
    </li>
{% endif %}